database-fly:
  datasource:
    url: jdbc:postgresql://localhost:9032/fly_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

database-hotel:
  datasource:
    url: jdbc:postgresql://localhost:9032/hotel_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

database-account:
  datasource:
    url: jdbc:postgresql://localhost:9032/account_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
