version: '3.7'

services:
  da_postgresql:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 9032:5432
#    volumes:
#      - ./docker/postgresql/database:/docker-entrypoint-initdb.d